# feature_symphony_tool/config/config.yaml
# Copy this to config.yaml and fill in your values.

# OpenRouter Configuration
# Your OpenRouter API Key.
# IMPORTANT: It's highly recommended to set this via the OPENROUTER_API_KEY environment variable
# (e.g., in an .env file) instead of hardcoding it here for security.
# The tool will ONLY use the OPENROUTER_API_KEY environment variable.
openrouter_api_key_required: true # Reminder that API key is needed via env

# OpenRouter model to use for generating feature slice guides.
# Available models: "anthropic/claude-3-7-sonnet", "openai/gpt-4o", "google/gemini-1.5-pro", etc.
openrouter_model_guide_generation: "anthropic/claude-3-7-sonnet-20250219"

# Aider Configuration
# List of global context files to always include with Aider.
# These paths are relative to the root of the project where you run the symphony tool.
aider_global_context_files:
  - "README.md"
  # - "src/core_logic.py"
  # - "docs/architecture.md"

# Output Configuration
# Directory where the generated feature_slice_guide_*.md files will be saved.
# This path is relative to the root of the project where you run the symphony tool.
guides_output_directory: "docs/feature_guides" # Example: "project_docs/generated_guides"

# Tmux session name prefix for Aider runs
# The actual session name will be: {tmux_session_prefix}_{RUN_ID}
tmux_session_prefix: "symphony_aider"

# --- Advanced ---
# Optional: Directory within feature_symphony_tool to store logs and intermediate files for each run.
# If empty, no run-specific subdirectories are created by the tool for its own artifacts.
# Tool's internal run artifacts directory (relative to feature_symphony_tool location)
# Example: "runs" will create feature_symphony_tool/runs/RUN_ID/...
tool_run_artifacts_dir: "runs" 